---

- name: "Add nginx user in {{ steamengine_project_user }} group"
  ansible.builtin.user:
    name: "www-data"
    groups: "{{ steamengine_project_user }}"
    append: true
  when: ansible_os_family != 'RedHat'
  tags:
    - steamengine_runtime_sf

- name: "Add nginx user in {{ steamengine_project_user }} group"
  ansible.builtin.user:
    name: "{{ item }}"
    groups: "{{ steamengine_project_user }}"
    append: true
  when: ansible_os_family == 'RedHat'
  loop:
    - "nginx" # nginx user for statics
    - "apache" # php-fpm process for php
  tags:
    - steamengine_runtime_sf
