---

- name: Verify build extension
  assert:
    that: (steamengine_build_url | basename | splitext)[1] == ".war"
  when: steamengine_build_url is defined
  tags:
    - steamengine_deploy_tomcat7

- name: Verify conf sources
  assert:
    that: steamengine_project_configuration_template_path is undefined or steamengine_project_configuration is undefined
  tags:
    - steamengine_deploy_tomcat7
