---

- name: Create configuration file
  template:
    src: "project_properties.conf.j2"
    dest: "{{ steamengine_conf_path }}/project_env.conf"
    owner: "{{ steamengine_project_user }}"
    group: "{{ steamengine_app_user }}"
    mode: u=rw,g=r,o=
  when: steamengine_project_configuration is defined
  notify:
    - "{{ steamengine_project_name }} restart"
  tags:
    - steamengine_deploy_tomcat7

- name: Create external configuration file
  template:
    src: "{{ steamengine_project_configuration_template_path }}"
    dest: "{{ steamengine_conf_path }}/project_env.conf"
    owner: "{{ steamengine_project_user }}"
    group: "{{ steamengine_app_user }}"
    mode: u=rw,g=r,o=
  when: steamengine_project_configuration_template_path is defined
  notify:
    - "{{ steamengine_project_name }} restart"
  tags:
    - steamengine_deploy_tomcat7

- name: Create tomcat directory
  file:
    path: "{{ steamengine_project_root_path }}/tomcat"
    owner: "{{ steamengine_project_user }}"
    group: "{{ steamengine_app_user }}"
    mode: u=rwx,g=rx,o=
    state: directory
  tags:
    - steamengine_deploy_tomcat7

- name: Download tomcat
  get_url:
    url: "{{ steamengine_tomcat7_tomcat_url }}"
    dest: "{{ steamengine_project_root_path }}/tomcat_{{ steamengine_tomcat7_tomcat_version }}.tar.gz"
    checksum: "sha512:{{ steamengine_tomcat7_tomcat_sha512 }}"
    owner: "{{ steamengine_project_user }}"
    group: "{{ steamengine_app_user }}"
    mode: u=rwx,g=rx,o=
  register: get_url_tomcat
  notify:
    - "{{ steamengine_project_name }} restart"
  tags:
    - steamengine_deploy_tomcat7

- name: Unzip tomcat
  unarchive:
    src: "{{ steamengine_project_root_path }}/tomcat_{{ steamengine_tomcat7_tomcat_version }}.tar.gz"
    dest: "{{ steamengine_project_root_path }}/tomcat"
    owner: "{{ steamengine_project_user }}"
    group: "{{ steamengine_app_user }}"
    mode: u=rwx,g=rx,o=
    remote_src: true
    extra_opts: [--strip-components=1]
  when: get_url_tomcat.changed
  tags:
    - steamengine_deploy_tomcat7

- name: Remove default tomcat deployment
  file:
    path: "{{ steamengine_project_root_path }}/tomcat/webapps"
    state: absent
  when: get_url_tomcat.changed
  tags:
    - steamengine_deploy_tomcat7

- name: Remove default tomcat deployment (2)
  file:
    path: "{{ steamengine_project_root_path }}/tomcat/webapps"
    state: directory
    owner: "{{ steamengine_project_user }}"
    group: "{{ steamengine_app_user }}"
    mode: u=rwx,g=rx,o=
  when: get_url_tomcat.changed
  tags:
    - steamengine_deploy_tomcat7

- name: Create tomcat ROOT deployment
  file:
    path: "{{ steamengine_project_root_path }}/tomcat/webapps/ROOT"
    state: directory
    owner: "{{ steamengine_project_user }}"
    group: "{{ steamengine_app_user }}"
    mode: u=rwx,g=rx,o=
  when: get_url_tomcat.changed
  tags:
    - steamengine_deploy_tomcat7

- name: Create tomcat working directory
  file:
    path: "{{ steamengine_project_root_path }}/tomcat/work"
    state: directory
    owner: "{{ steamengine_project_user }}"
    group: "{{ steamengine_app_user }}"
    mode: u=rwx,g=rwx,o=
  when: get_url_tomcat.changed
  tags:
    - steamengine_deploy_tomcat7

- name: Create tomcat temp directory
  file:
    path: "{{ steamengine_project_root_path }}/tomcat/temp"
    state: directory
    owner: "{{ steamengine_project_user }}"
    group: "{{ steamengine_app_user }}"
    mode: u=rwx,g=rwx,o=
  when: get_url_tomcat.changed
  tags:
    - steamengine_deploy_tomcat7

- name: Create tomcat configuration file
  template:
    src: "tomcat7.server.xml.j2"
    dest: "{{ steamengine_project_root_path }}/tomcat/conf/server.xml"
    owner: "{{ steamengine_project_user }}"
    group: "{{ steamengine_app_user }}"
    mode: u=rwx,g=rx,o=
  notify:
    - "{{ steamengine_project_name }} restart"
  tags:
    - steamengine_deploy_tomcat7

- name: "Download build {{ steamengine_build_url }}"
  get_url:
    url: "{{ steamengine_build_url }}"
    dest: "{{ steamengine_project_root_path }}/project.war"
    checksum: "{{ steamengine_build_checksum }}"
    owner: "{{ steamengine_project_user }}"
    group: "{{ steamengine_app_user }}"
    mode: u=rwx,g=rx,o=
  register: get_url_build
  notify:
    - "{{ steamengine_project_name }} fixpermissions"
    - "{{ steamengine_project_name }} restart"
  tags:
    - steamengine_deploy_tomcat7

- name: check if steamengine bin exists
  stat:
    path: "{{ steamengine_bin_path }}/steamengine"
  register: steamengine_bin
  when: get_url_build.changed

- name: "Fix permissions"
  command: "/{{ steamengine_project_name }}/bin/steamengine fixpermissions"
  when: get_url_build.changed and steamengine_bin.stat.exists
  tags:
    - steamengine_deploy_tomcat7

- name: Update webapps/ROOT directory
  include_tasks: include/update_from_archive.yml
  vars:
    archive_path: "{{ steamengine_project_root_path }}/project.war"
    dest_path: "{{ steamengine_project_root_path }}/tomcat/webapps/ROOT"
  when: get_url_build.changed
  args:
    apply:
      tags:
        - steamengine_deploy
        - steamengine_deploy_tomcat7
  tags:
    - steamengine_deploy_tomcat7
