---
- name: Converge
  hosts: instance
  become: true

  pre_tasks:
    - include_tasks: "../resources/setup_{{ ansible_os_family | lower }}.yml"

  roles:
    - role: lean_delivery.java
      vars:
        java_distribution: adoptopenjdk
        java_major_version: 8
        java_minor_version: 252
        adoptopenjdk_impl: openj9
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
      vars:
        steamengine_project_name: play2_test
        steamengine_project_type: play
        steamengine_build_url: https://delivery.steamulo.org/SteamEngineV2_tests/play2_test.zip
        steamengine_build_checksum: sha1:9c6df9e945380af0732b028718c5d1a47c5be441
        steamengine_project_configuration_base_name: "application"
        steamengine_project_configuration:
          play:
            http:
              secret:
                key: "azfafzefezfbzelgbzebfganfdmazofnzmoenfoazen"
